// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.Browser;

#nullable disable

namespace MyProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250921163810_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MyProject.Data.SinhVienData", b =>
                {
                    b.Property<string>("oid")
                        .HasColumnType("TEXT")
                        .HasColumnName("oid");

                    b.Property<string>("chuyen_nganh")
                        .HasColumnType("TEXT")
                        .HasColumnName("chuyen_nganh");

                    b.Property<string>("nam_hoc")
                        .HasColumnType("TEXT")
                        .HasColumnName("nam_hoc");

                    b.Property<string>("ngay_sinh")
                        .HasColumnType("TEXT")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("que_quan")
                        .HasColumnType("TEXT")
                        .HasColumnName("que_quan");

                    b.Property<string>("ten")
                        .HasColumnType("TEXT")
                        .HasColumnName("ten");

                    b.HasKey("oid");

                    b.ToTable("sinhvien");
                });
#pragma warning restore 612, 618
        }
    }
}
